# Generated by Django 4.0.5 on 2022-06-25 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 6, 25))),
                ('season', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2036')], max_length=200)),
                ('plate_appearance', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=200)),
                ('first_runnner', models.BooleanField(default=False)),
                ('second_runner', models.BooleanField(default=False)),
                ('third_runner', models.BooleanField(default=False)),
                ('hand', models.CharField(choices=[('右', '右'), ('左', '左')], max_length=200)),
                ('ball_type', models.CharField(choices=[('4-seam-fastball', '4-seam-fastball'), ('2seam-fastball', '2-seam-fastball'), ('slider', 'slider'), ('cut', 'cut'), ('curve', 'curve'), ('sinker', 'sinker'), ('change-up', 'change-up'), ('splitter', 'splitter')], max_length=200)),
                ('mph', models.CharField(choices=[('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100'), ('101', '101'), ('102', '102')], default='90', max_length=200)),
                ('result', models.CharField(choices=[('strikeout', 'strikeout'), ('groundout', 'groundout'), ('flyout', 'flyout'), ('single', 'single'), ('double', 'double'), ('triple', 'triple'), ('homerun', 'homerun'), ('four-ball', 'four-ball'), ('dead-ball', 'dead-ball'), ('sacrifice-fly', 'sacrifice-fly'), ('sacrifice-bunt', 'sucrifice-bunt')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
